name: Build Blink Lag DLL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: MSVC Developer Command Prompt Kurulumu
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: C++ Kodunu DLL Olarak Derle
      run: |
        cl.exe /EHsc /O2 /LD main.cpp /link /OUT:BlinkHook.dll User32.lib

    - name: Derlenen DLL Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: BlinkLag-Windows-DLL
        path: BlinkHook.dll
        
